language: nix
nix: 2.1.1

env:
  - GOPATH=${HOME}
  - PATH=${PATH}:${GOPATH}/bin
  - TRAVIS_BUILD_DIR=${${GOPATH}/src/github.com/mpoquet/netorcai}

script:
  - echo "current dir: $(realpath .)"
  - nix-shell -p bash --command 'echo Hello from nix-shell!'
