# appveyor.yml
clone_folder: c:\gopath\src\github.com\netorcai\netorcai

environment:
  GOPATH: c:\gopath

stack: go 1.11

build_script:
  - go get ./
  - go get ./cmd/netorcai
  - go build ./cmd/netorcai

after_build:
  - set PATH=%PATH%;c:\gopath\bin
